version: "2"
services:
  db:
    build: ./db/.
    image: amigo-nodejs
    ports:
      - "9000:5432"
  web:
    build: ./api/.
    image: amigo-db
    environment:
      - NODE_ENV=TEST
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    volumes:
      - ./api/amigo/:/var/www/amigo/api